### ISSUE TITLE
looks like the shade library is breaking this script

### ISSUE THREAD

**Issue by naved001** [larsks/os-placement-tools#2]
```
(osc) naved::~/os-placement-tools$python check_placement.py 
Traceback (most recent call last):
  File "check_placement.py", line 177, in <module>
    main()
  File "check_placement.py", line 130, in main
    instance = cloud_api.get_server(instance_uuid, all_projects=True)
  File "/home/naved/osc/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 3200, in get_server
    return self._expand_server(server, detailed, bare)
  File "/home/naved/osc/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 3208, in _expand_server
    return meta.add_server_interfaces(self, server)
  File "/home/naved/osc/local/lib/python2.7/site-packages/shade/meta.py", line 433, in add_server_interfaces
    server['addresses'] = _get_supplemental_addresses(cloud, server)
  File "/home/naved/osc/local/lib/python2.7/site-packages/shade/meta.py", line 411, in _get_supplemental_addresses
    fixed_net = fixed_ip_mapping[fip['fixed_ip_address']]
KeyError: u'10.0.0.22'
```
`fixed_ip_mapping` has nothing in it. I commented out the `get_supplemental_addresses` and then it worked.

**Comment by larsks** [comment]
So noted...but yeah, that seems pretty deep in the `shade` library, so not much we can do to fix it from here. I'm going to leave this open for a bit and see if I get around to opening an upstream issue.
